#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/variables
- name: use template /home/muelmar/vars_output.txt to show vars
  ansible.builtin.template:
    src: templates/vars_output.j2
    dest: /home/muelmar/vars_output.txt
    owner: muelmar
